---

- name: Become Test
  hosts: all
  tasks: 
    - name: Install RHEL/Fedora Web Console (Cockpit)
      include_role:
        name: fedora.linux_system_roles.cockpit
      vars:
        cockpit_packages: default
        
    - name: Configure Firewall for Web Console
      include_role:
        name: fedora.linux_system_roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
